# Numpy
### Если задания покажутся сложными, рекомендую пройти краткий курс по основам numpy [ссылка1](https://stepik.org/lesson/241329/step/1?unit=213910), [ссылка2](https://stepik.org/lesson/16462/step/1?unit=4283)

In [2]:
import numpy as np
import random
import scipy.stats as sps
import cv2


### Задание 1
В первой задаче вам предлагается перемножить две квадратные матрицы двумя способами -- без использования пакета ***numpy*** и с ним.

In [3]:
# Для генерации матриц используем функцию random -- она используется для генерации случайных объектов
# функция sample создает случайную выборку. В качестве аргумента ей передается кортеж (i,j),
# здесь i -- число строк, j -- число столбцов.
a = np.random.sample((100, 100))
b = np.random.sample((100, 100))
# выведите размерность (ранг) каждой матрицы с помощью функции ndim.
# Используйте функцию shape, которая выводит размер матрицы (i строк, j столбцов)
# ========
print("ранг a =",a.ndim, "\nранг b =", b.ndim)
print("размер матрицы a =",a.shape,"\nразмер матрицы b =",b.shape)
# ========
print(a)
print(b)

ранг a = 2 
ранг b = 2
размер матрицы a = (100, 100) 
размер матрицы b = (100, 100)
[[0.03676505 0.47889999 0.32867011 ... 0.06758005 0.34000945 0.78056539]
 [0.71797022 0.98501063 0.40649386 ... 0.48350105 0.37866554 0.90387053]
 [0.26707701 0.45701955 0.06907701 ... 0.67864691 0.38932641 0.4075093 ]
 ...
 [0.29218556 0.45466461 0.8290205  ... 0.77887163 0.6378048  0.54289658]
 [0.11992891 0.17142583 0.04516502 ... 0.8256304  0.57234325 0.97659129]
 [0.0158105  0.40884705 0.68348226 ... 0.50585481 0.54417032 0.29347162]]
[[0.91728586 0.67880511 0.39259892 ... 0.76190354 0.58969233 0.22827416]
 [0.44748102 0.59421336 0.99283657 ... 0.50904138 0.81105567 0.25802493]
 [0.96729907 0.18139258 0.78420856 ... 0.96058661 0.35580156 0.71519166]
 ...
 [0.68895548 0.12657005 0.18611441 ... 0.78484125 0.68783657 0.71843505]
 [0.4851026  0.78766664 0.98893138 ... 0.7231414  0.46744015 0.03957501]
 [0.71107762 0.28522379 0.01869935 ... 0.61802262 0.19211505 0.3524253 ]]


Без использования numpy

In [4]:
def mult(a, b):
    result = [[0 for i in range(len(b[0]))] for j in range(len(a))]
    for i in range(len(a)):
      for j in range(len(b[0])):
        result[i][j] = sum(a[i][k] * b[k][j] for k in range(len(b)))
    return result

C использованием numpy

In [5]:
def np_mult(a, b):
    result = None
    result = np.dot(a, b)
    return result

In [6]:
%%time
# засечем время работы функции без NumPy
M1 = mult(a, b)

CPU times: user 675 ms, sys: 0 ns, total: 675 ms
Wall time: 678 ms


In [7]:
%%time
# засечем время работы функции с NumPy
M2 = np_mult(a, b)

CPU times: user 805 µs, sys: 0 ns, total: 805 µs
Wall time: 5.5 ms


In [8]:
# проверим корректность
np.abs(np.array(M1) - M2).sum()

1.525535253676935e-11

### Задание 2

Вам подаются на вход два вектора `a` и `b` в трехмерном пространстве. Заполните их случайными числами. Реализуйте их скалярное произведение с помощью  `NumPy` и без. Засеките время работы, как это показано в заданиях выше.

In [9]:
a = np.random.sample((1, 3))
a = list(a)[0]
b = np.random.sample((1, 3))
b = list(b)[0]
print(a, b)

[0.76007562 0.12913149 0.12668336] [0.28138144 0.65068433 0.6573588 ]


In [14]:
def scalar_product(a,b):
    s = 0
    for i in range(len(a)):
        s += a[i] * b[i]
    return s

In [15]:
def np_scalar_product(a,b):
    s = 0
    s = np.dot(a, b)
    return s

In [16]:
%time product_1 = scalar_product(a,b)
%time product_2 = np_scalar_product(a,b)
# проверим корректность:
np.abs(product_1 - product_2).sum()

CPU times: user 22 µs, sys: 4 µs, total: 26 µs
Wall time: 31 µs
CPU times: user 42 µs, sys: 6 µs, total: 48 µs
Wall time: 66 µs


0.0

Почему методы ***numpy*** оказываются эффективнее? Что вы можете сказать о скорости вычислений в NumPy?

**Ответ:** Многие операции в NumPy могут быть выполнены на массивах целиком, без явного использования циклов. Это позволяет избежать медленной итерации по элементам массива и использовать оптимизированные реализации операций на уровне языка C.


------------------

### Задание 3
Напишите функцию, которая находим сумму четных диагональныех элементов квадратной матрицы. Если таких элементов нет, то вывести `0`.

In [17]:
# функция, решающая задачу с помощью NumPy
def np_diag_2k(a):
  res = None
  res = sum([m for m in np.diagonal(a) if m % 2 == 0])
  return res

In [18]:
# зададим некоторую квадратную матрицу
a = np.random.randint(1, 10, size=(5, 5))
a

array([[8, 8, 3, 5, 7],
       [9, 2, 7, 9, 8],
       [6, 6, 7, 1, 2],
       [6, 6, 1, 6, 4],
       [5, 8, 7, 9, 2]])

In [19]:
%%time
# засечем время работы функции с NumPy
np_diag_2k(a)

CPU times: user 59 µs, sys: 0 ns, total: 59 µs
Wall time: 66.3 µs


18

### Задание 4
На вход дан двумерный массив $X$. Напишите функцию, которая для каждой строчки $x = (x_1, x_2, \ldots, x_n)$ массива $X$  строит строчку $s = (s_1, s_2, \ldots, s_n)$, где $s_k=\frac{x_1+...+x_k}{k}$, а затем выдаёт массив из построенных строчек. Используйте библиотеку numpy (вам поможет функция cumsum). Выходом функции должен быть двумерный массив той же формы, что и $X$.

In [22]:
# функция, решающая задачу с помощью NumPy
def np_sec_av(*A):
    result = None
    a = np.array(A)
    cs = np.cumsum(a, axis=1)
    result = cs.reshape(len(a), cs.size // len(a))
    return result

In [23]:
# зададим некоторую последовательность и проверим ее на ваших функциях.
# функция должна работать ~ в 50 раз быстрее, чем без Numpy
A = sps.uniform.rvs(size=10**3)
print(A)

%time S2 = np_sec_av(A)

[0.83747156 0.00271271 0.07130133 0.58407232 0.8003433  0.59278526
 0.49189206 0.11022888 0.17961336 0.09314857 0.10622143 0.92923143
 0.99831112 0.11902586 0.21909809 0.49385586 0.17573317 0.39075408
 0.38815943 0.39513609 0.74419693 0.3599134  0.48554628 0.94321034
 0.74929444 0.32809551 0.17607966 0.07474354 0.08281773 0.69513035
 0.17718923 0.70537488 0.71402463 0.16506921 0.4313085  0.51022651
 0.52246576 0.02451672 0.43084558 0.31111088 0.79103027 0.51047662
 0.5067569  0.03264293 0.1755651  0.70060736 0.25813572 0.55657037
 0.25670548 0.32580161 0.07361722 0.56868078 0.57360995 0.17979641
 0.43866031 0.84558315 0.01211352 0.48957562 0.19114368 0.34497988
 0.49891055 0.47125903 0.29270065 0.53183603 0.22398558 0.56403668
 0.01090903 0.19050679 0.80057326 0.56114026 0.25820459 0.56722239
 0.65475134 0.59448428 0.37557718 0.08610161 0.47092038 0.31655302
 0.89326994 0.52158324 0.05804189 0.8572546  0.8995229  0.54143116
 0.53847218 0.15714137 0.86787853 0.01372072 0.59958551 0.4216

### Задание 5
Написать функцию для кодирование массива (Run-length encoding). Все подряд повторения элементов функция сжимает в один элемент и считает количество повторений. Функция возвращает кортеж из двух векторов одинаковой длины. Первый содержит элементы, а второй — сколько раз их нужно повторить.

Пример: encode(np.array([1, 2, 2, 3, 3, 1, 1, 5, 5, 2, 3, 3])) = (np.array[1, 2, 3, 1, 5, 2, 3]), np.array[1, 2, 2, 2, 2, 1, 2])

In [26]:
# функция, решающая задачу с помощью NumPy
def np_encode(a):
    result = None
    i = np.where(a[:-1] != a[1:])[0]
    i = np.concatenate((i, [len(a) - 1]))
    spl = np.split(a, i + 1)
    v, c = np.unique(spl, return_counts=True)
    result = v, c
    return result

In [27]:
from itertools import groupby
X = np.array([1, 2, 2, 3, 3, 1, 1, 5, 5, 2, 3, 3])
%time x, num = np_encode(X)

/usr/local/lib/python3.10/dist-packages/numpy/lib/arraysetops.py:272: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  ar = np.asanyarray(ar)


ValueError: ignored

### Задание 6

Пусть задан некоторый одномерный массив $X$. Надо построить новый массив, где все элементы с нечетными индексами требуется заменить на число $a$ (если оно не указано, то на 1). Все элементы с четными индексами нужно возвести в куб. Затем записать элементы в обратном порядке относительно их позиций. Массив $X$ при этом должен остаться *без изменений*. В конце требуется слить массив X с преобразованным X и вывести в обратном порядке.  

Пример:  
X = [100, 200, 300, 400, 500] -> [100, a, 300, a, 500] -> [500^3, a, 300^3, a, 100^3] -> склеиваем -> [100, 200, 300, 400, 500, 500^3, a, 300^3, a, 100^3]

In [33]:
# функция, решающая задачу с помощью NumPy
from copy import copy

def np_transformation(X, a=1):
    """
    param X: array
    """
    result = None
    x = np.array(X)
    res = x.copy()
    for i in range(len(b)):
        if i % 2 == 0: res[i] = res[i] ** 3
        else: res[i] = a
    res = list(reversed(res))
    result = np.hstack((x, res))
    return result

In [34]:
X = np.array([i for i in range(1, 10, 2)])
# функция должна работать ~ в 20 раз быстрее, чем без Numpy
%time S2 = np_transformation(X, 5)

CPU times: user 106 µs, sys: 0 ns, total: 106 µs
Wall time: 113 µs
